name: job3_v0
on:
  workflow_dispatch:
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - run: echo "hello job2" > test.txt
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
    - name: Lancer du PoweShell
      run: Write-Host "Coucou"
      shell: pwsh
    - name: Python
      run: print("Coucou")
      shell: python
