name: "matrix - exercice 3"
on: 
  workflow_dispatch:
jobs:
  build:
    strategy:
      max-parallel: 2
      matrix:
        server: [prod1, prod2, prod3, prod4, prod5, prod6, prod7, prod8]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy application
       - name: Deploy application
         run: echo "Deploy on ${{ matrix.server }}"
