name: matrice_ex
on:
  workflow_dispatch:
jobs:
  job-matrix:
    strategy:
      matrix:
        os: [ubuntu-latest,  macos-latest,  windows-latest]]
        node: [10,12]
        exclude:
        - os: ubuntu-latest
    runs-on: $${{ matrix.os }}
    steps:
    - run: echo $${{ matrix.os }}
