name: matrice_ex
on:
  workflow_dispatch:
jobs:
  job-matrix:
    strategy:
      matrix:
        os: [ubuntu-latest,  macos-latest,  windows-latest]]
        node: [10,12]
    runs-on: $${{ matrix.os }}

