name: matrice

on:
  workflow_dispatch:
jobs:
  monjob:
    strategy:
    matrix:
    os: [ubuntu-latest,macos-latest,windows-latest]
  runs-on: $${{ matrix.os }}
  steps:
  - run: echo $${{ matrix.os }}
