name: step ex1
on: 
  workflow_dispatch:
jobs:
  Message:
    runs-on: ubuntu-latest
    steps:
    - uses: lgmorand/github-action-hello@v2
      with:
        firstname: bruno
        firstname2: prskawiec
    - uses: user/fake-action@1.1.0
