name: java_test
on:
  workflow_dispatch:
jobs:
  build:
    strategy:
      matrix:
        java: [8, 11]
        testing: [false]
        include:
          - java: 14
            testing: true
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.testing }}
    steps:
    - run: echo $${{ matrix.java }}
  
